TRUNCATE TABLE commerce.marketplace_products RESTART IDENTITY CASCADE;

INSERT INTO commerce.marketplace_products
    (slug, name, short_description, long_description, price, image_url, categories, tags, rating, rating_count, inventory_status, badges, contraindications)
VALUES
    (
        'paracetamol-500mg-strip',
        'Paracetamol 500 mg Strip',
        'Pereda demam dan nyeri dengan dosis efektif.',
        $$Paracetamol 500 mg membantu meredakan demam serta nyeri ringan hingga sedang. Konsumsi setelah makan dan ikuti dosis dari tenaga kesehatan Anda.$$,
        18000,
        'https://images.unsplash.com/photo-1580281658629-1796132cc0c3?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['analgesik','demam','OTC'],
        4.6,
        182,
        'in-stock',
        ARRAY['Supabase'],
        '[{"id":"allergy-paracetamol","type":"allergy","value":"acetaminophen","severity":"caution","note":"Hentikan pemakaian bila muncul reaksi hipersensitivitas."}]'::jsonb
    ),
    (
        'ibuprofen-400mg-botol',
        'Ibuprofen 400 mg Botol',
        'Anti-inflamasi untuk nyeri sendi dan otot.',
        $$Ibuprofen 400 mg memberikan efek anti-inflamasi sekaligus analgesik. Gunakan setelah makan dan hindari bila memiliki riwayat tukak lambung berat.$$,
        32000,
        'https://images.unsplash.com/photo-1580281658629-1796132cc0c3?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['NSAID','nyeri','inflamasi'],
        4.4,
        96,
        'low-stock',
        ARRAY['Supabase'],
        '[{"id":"allergy-nsaid","type":"allergy","value":"NSAID","severity":"danger","note":"Pasien dengan riwayat alergi terhadap NSAID harus menghindari ibuprofen."}]'::jsonb
    ),
    (
        'amoxicillin-500mg-kapsul',
        'Amoxicillin 500 mg Kapsul',
        'Antibiotik spektrum luas untuk infeksi bakteri peka.',
        $$Amoxicillin bekerja menghambat sintesis dinding sel bakteri. Konsumsi sesuai durasi terapi dokter dan jangan hentikan sebelum waktunya untuk mencegah resistensi.$$,
        54000,
        'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['antibiotik','spektrum-luas'],
        4.7,
        143,
        'in-stock',
        ARRAY['Resep'],
        '[{"id":"allergy-penicillin","type":"allergy","value":"penisilin","severity":"danger","note":"Hindari penggunaan bila memiliki riwayat alergi terhadap penisilin atau beta-laktam lain."}]'::jsonb
    ),
    (
        'metformin-500mg-er',
        'Metformin 500 mg Lepas Lambat',
        'Biguanid oral untuk kontrol glikemik pasien diabetes tipe 2.',
        $$Metformin meningkatkan sensitivitas insulin dan menurunkan produksi glukosa hati. Kombinasikan dengan pola makan sehat dan aktivitas fisik teratur.$$,
        68000,
        'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['diabetes','biguanid'],
        4.5,
        201,
        'in-stock',
        ARRAY['Direkomendasikan'],
        '[]'::jsonb
    ),
    (
        'atorvastatin-20mg-tablet',
        'Atorvastatin 20 mg Tablet',
        'Statin untuk menurunkan kolesterol LDL dan trigliserida.',
        $$Atorvastatin menurunkan kadar kolesterol dengan menghambat enzim HMG-CoA reduktase. Konsumsi malam hari dan pantau fungsi hati secara berkala.$$,
        89000,
        'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['dislipidemia','statin'],
        4.3,
        118,
        'in-stock',
        ARRAY['Monitoring'],
        '[{"id":"medication-interaction","type":"medication","value":"statin","severity":"warning","note":"Waspadai interaksi dengan obat lain yang menggunakan metabolisme CYP3A4."}]'::jsonb
    ),
    (
        'omeprazole-20mg-kapsul',
        'Omeprazole 20 mg Enteric Capsule',
        'Inhibitor pompa proton untuk gastritis dan refluks asam.',
        $$Omeprazole menekan produksi asam lambung. Konsumsi sebelum makan utama dan batasi penggunaan lebih dari 14 hari tanpa konsultasi medis.$$,
        45000,
        'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Obat'],
        ARRAY['GERD','pencernaan'],
        4.6,
        154,
        'in-stock',
        ARRAY['Supabase'],
        '[]'::jsonb
    ),
    (
        'salbutamol-inhaler-mdi',
        'Salbutamol Inhaler MDI',
        'Bronkodilator kerja cepat untuk serangan asma.',
        $$Salbutamol bekerja sebagai agonis β2 untuk merelaksasi otot bronkus. Gunakan sesuai kebutuhan saat serangan asma dan catat frekuensi pemakaian harian.$$,
        125000,
        'https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Perangkat'],
        ARRAY['asma','bronkodilator','rescue'],
        4.8,
        87,
        'low-stock',
        ARRAY['Stok terbatas'],
        '[]'::jsonb
    ),
    (
        'vitamin-c-1000mg-effervescent',
        'Vitamin C 1000 mg Effervescent',
        'Menjaga daya tahan tubuh harian.',
        $$Suplemen vitamin C effervescent membantu menjaga imunitas terutama saat aktivitas padat. Larutkan dalam segelas air sebelum diminum.$$,
        45000,
        'https://images.unsplash.com/photo-1611078489935-0cb964de46d6?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Vitamin'],
        ARRAY['imunitas','suplementasi'],
        4.8,
        245,
        'in-stock',
        ARRAY['Promo 10%'],
        '[]'::jsonb
    ),
    (
        'omega-3-fish-oil',
        'Omega-3 Fish Oil',
        'EPA DHA untuk kesehatan jantung dan otak.',
        $$Minyak ikan berkualitas tinggi yang mendukung kesehatan jantung, otak, dan sendi. Dilengkapi vitamin E sebagai antioksidan.$$,
        79000,
        'https://images.unsplash.com/photo-1580281658629-1796132cc0c3?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Vitamin'],
        ARRAY['omega','jantung'],
        4.7,
        122,
        'in-stock',
        ARRAY['Supabase'],
        '[]'::jsonb
    ),
    (
        'probiotik-gastro-balance',
        'Probiotik Gastro Balance',
        'Strain probiotik pilihan untuk kesehatan cerna.',
        $$Mengandung kombinasi Lactobacillus dan Bifidobacterium untuk membantu menyeimbangkan flora usus dan mengurangi keluhan pencernaan ringan.$$,
        52000,
        'https://images.unsplash.com/photo-1610395219790-54aa72d4f89f?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Vitamin'],
        ARRAY['pencernaan','probiotik'],
        4.4,
        47,
        'in-stock',
        ARRAY['Direkomendasikan'],
        '[]'::jsonb
    ),
    (
        'glucometer-kit-smart',
        'Glucometer Kit Smart',
        'Monitor gula darah dengan koneksi aplikasi.',
        $$Glucometer dengan konektivitas Bluetooth yang menampilkan riwayat gula darah di aplikasi. Termasuk 25 strip uji dan jarum lancet.$$,
        285000,
        'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Perangkat'],
        ARRAY['diabetes','monitoring','digital'],
        4.7,
        73,
        'in-stock',
        ARRAY['Direkomendasikan'],
        '[{"id":"med-metformin","type":"medication","value":"metformin","severity":"warning","note":"Pastikan pencatatan terintegrasi dengan terapi metformin aktif Anda."}]'::jsonb
    ),
    (
        'konsultasi-psikologi-online',
        'Paket Konsultasi Psikologi Online',
        '3 sesi konseling daring dengan psikolog tersertifikasi.',
        $$Konseling psikologi secara daring untuk membantu manajemen stres, kecemasan, dan peningkatan kualitas tidur. Setiap sesi berlangsung 50 menit.$$,
        350000,
        'https://images.unsplash.com/photo-1526256262350-7da7584cf5eb?auto=format&fit=crop&w=1200&q=80',
        ARRAY['Layanan'],
        ARRAY['mental','konseling'],
        4.9,
        41,
        'in-stock',
        ARRAY['Bundle 3x'],
        '[]'::jsonb
    );
