[phases.setup]
nixPkgs = ['nodejs_22'] # (Atau nodejs_20, sesuaikan dengan yang kamu pilih sebelumnya)

[phases.install]
cmds = [
    'npm install -g pnpm@9',
    'npx pnpm install'
]

[phases.build]
cmds = ['npx pnpm run build']

# Tambahkan bagian ini untuk menghentikan Nixpacks menggunakan 'deno'
[start]
cmd = 'npx pnpm start'